export const ENV_HASH_ROUNDS_KEY = 'HASH_ROUNDS';
export const ENV_JWT_SECRET_KEY = 'JWT_SECRET';
export const ENV_AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID';
export const ENV_AWS_SECRET_ACCESS_KEY = 'AWS_SECRET_ACCESS_KEY';
export const ENV_AWS_REGION = 'AWS_REGION';
export const ENV_AWS_BUCKET_NAME = 'AWS_BUCKET_NAME';
